### ISSUE TITLE
JsonProperty annotaion is ignored

### ISSUE THREAD

**Issue by Denis-D-M** [linsage/java2json#16]
I assume it's just not supported, but anyway, I expected it's gonna work
![image](https://user-images.githubusercontent.com/55101583/175901139-e8fd3526-657f-4127-8de4-6ed8ac005bac.png)

**Comment by Enokiy** [comment]
It seems the author has stopped to maintaining this plugin, I add some code to support @JsonProperty annotation  and created a pull request. Before the author merge the code,you can get the updated plugin from https://github.com/Enokiy/java2json/blob/master/java2json.jar

**Comment by Denis-D-M** [comment]
@Enokiy Seems to be working, thanks! I wanted to do it myself on the weekend, but you were faster than me :D
