### ISSUE TITLE
能把字段的注解也转换到 json 里吗?

### ISSUE THREAD

**Issue by kid1412621** [linsage/java2json#3]
convert bean field comment into JSON.

**Comment by linsage** [comment]
新增 @comment字段来存储注释

**Comment by kid1412621** [comment]
> @comment

但是这样不好对应啊, 我想的是这样:
```json
{
"name": "whateverName" // 名字  
}
```
当然这种 json with comment 不是官方标准

**Comment by linsage** [comment]
这样会导致json解析错误

**Comment by linsage** [comment]
> > @comment
> 
> 但是这样不好对应啊, 我想的是这样:
> 
> ```json
> {
> "name": "whateverName" // 名字  
> }
> ```
> 
> 当然这种 json with comment 不是官方标准

这样会导致json解析错误
